spring.application.name=api-gateway



# Gateway chạy port 9000 (8080/8081/8082 đã dùng cho các services)
server.port=9000

# URL các service đích
services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082


# TODO 4.9: Issuer URI của Keycloak realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm
management.endpoints.web.exposure.include=health